---
format_version: '11'
default_step_lib_source: 'https://github.com/bitrise-io/bitrise-steplib.git'
project_type: other
trigger_map:
- push_branch: '*'
  workflow: primary
- pull_request_source_branch: '*'
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - cache-pull@2.5: {}
    - git-clone@6: {}
    - script@1:
        title: Do anything with Script step
        inputs:
        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# debug log\nset -x\n\n# write your script here\ndir\napt install rclone\nmkdir -p ~/.config/rclone\necho \"$rcloneconfig\" > ~/.config/rclone/rclone.conf\nif [ -d \"environment\" ]\nthen\n    echo \"Environment scripts dir exists, not cloning env-setup.\" \nelse\n    echo \"Environment scripts dir does not exist, cloning env-setup.\"\n\tgit clone  https://github.com/akhilnarang/scripts.git environment\n\tbash environment/setup/android_build_env.sh\nfi\nbash build.sh\nrclone copy $(pwd)/Flasher/*.zip ccache:vince\ncurl -s https://api.telegram.org/bot$BOT_API_KEY/sendMessage -d chat_id=$channelid -d text=\"Download link https://retarded-sprout.axsp.workers.dev/vince/($(pwd)/Flasher && ls *.zip\"\n# or run a script from your repository, like:\n# bash ./path/to/script.sh\n# not just bash, e.g.:\n# ruby ./path/to/script.r"
    - cache-push@2.6:
        inputs:
        - cache_paths: $BITRISE_SOURCE_DIR
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    stack: linux-docker-android-20.04
    machine_type_id: elite
